/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.databit.main;

/**
 *
 * @author Pralay
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePane = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        profilePicture = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        homeSel = new javax.swing.JPanel();
        homePane = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        project = new javax.swing.JPanel();
        projectSel = new javax.swing.JPanel();
        projectPane = new javax.swing.JPanel();
        projectLabel = new javax.swing.JLabel();
        data = new javax.swing.JPanel();
        dataSel = new javax.swing.JPanel();
        dataPane = new javax.swing.JPanel();
        dataLabel = new javax.swing.JLabel();
        withdraw = new javax.swing.JPanel();
        withdrawSel = new javax.swing.JPanel();
        withdrawPane = new javax.swing.JPanel();
        withdrawLabel = new javax.swing.JLabel();
        profile = new javax.swing.JPanel();
        profileSel = new javax.swing.JPanel();
        profilePane = new javax.swing.JPanel();
        profileLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        minmize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        resize = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1092, 656));

        sidePane.setBackground(new java.awt.Color(11, 19, 43));
        sidePane.setPreferredSize(new java.awt.Dimension(222, 489));
        sidePane.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(11, 19, 43));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profilePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profilePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/businessman.png"))); // NOI18N
        profilePicture.setFocusable(false);
        jPanel9.add(profilePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, 120));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(239, 247, 246));
        nameLabel.setText("Pralay Mandal");
        jPanel9.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        sidePane.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel11.setBackground(new java.awt.Color(11, 19, 43));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/power.png"))); // NOI18N
        jPanel11.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/setting.png"))); // NOI18N
        jPanel11.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 50));

        jPanel3.setBackground(new java.awt.Color(11, 19, 43));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 220, 20));

        sidePane.add(jPanel11, java.awt.BorderLayout.PAGE_END);

        jPanel12.setBackground(new java.awt.Color(11, 19, 43));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(28, 37, 65));
        home.setLayout(new java.awt.BorderLayout());

        homeSel.setBackground(new java.awt.Color(69, 213, 146));

        javax.swing.GroupLayout homeSelLayout = new javax.swing.GroupLayout(homeSel);
        homeSel.setLayout(homeSelLayout);
        homeSelLayout.setHorizontalGroup(
            homeSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        homeSelLayout.setVerticalGroup(
            homeSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        home.add(homeSel, java.awt.BorderLayout.LINE_START);

        homePane.setBackground(new java.awt.Color(28, 37, 65));

        homeLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(239, 247, 246));
        homeLabel.setText("Home");

        javax.swing.GroupLayout homePaneLayout = new javax.swing.GroupLayout(homePane);
        homePane.setLayout(homePaneLayout);
        homePaneLayout.setHorizontalGroup(
            homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        homePaneLayout.setVerticalGroup(
            homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        home.add(homePane, java.awt.BorderLayout.CENTER);

        jPanel12.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 220, 50));

        project.setBackground(new java.awt.Color(28, 37, 65));
        project.setLayout(new java.awt.BorderLayout());

        projectSel.setBackground(new java.awt.Color(11, 19, 43));

        javax.swing.GroupLayout projectSelLayout = new javax.swing.GroupLayout(projectSel);
        projectSel.setLayout(projectSelLayout);
        projectSelLayout.setHorizontalGroup(
            projectSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        projectSelLayout.setVerticalGroup(
            projectSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        project.add(projectSel, java.awt.BorderLayout.LINE_START);

        projectPane.setBackground(new java.awt.Color(11, 19, 43));

        projectLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        projectLabel.setForeground(new java.awt.Color(239, 247, 246));
        projectLabel.setText("New Projects");

        javax.swing.GroupLayout projectPaneLayout = new javax.swing.GroupLayout(projectPane);
        projectPane.setLayout(projectPaneLayout);
        projectPaneLayout.setHorizontalGroup(
            projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        projectPaneLayout.setVerticalGroup(
            projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        project.add(projectPane, java.awt.BorderLayout.CENTER);

        jPanel12.add(project, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 50));

        data.setBackground(new java.awt.Color(28, 37, 65));
        data.setLayout(new java.awt.BorderLayout());

        dataSel.setBackground(new java.awt.Color(11, 19, 43));

        javax.swing.GroupLayout dataSelLayout = new javax.swing.GroupLayout(dataSel);
        dataSel.setLayout(dataSelLayout);
        dataSelLayout.setHorizontalGroup(
            dataSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        dataSelLayout.setVerticalGroup(
            dataSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        data.add(dataSel, java.awt.BorderLayout.LINE_START);

        dataPane.setBackground(new java.awt.Color(11, 19, 43));

        dataLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        dataLabel.setForeground(new java.awt.Color(239, 247, 246));
        dataLabel.setText("My Entries");

        javax.swing.GroupLayout dataPaneLayout = new javax.swing.GroupLayout(dataPane);
        dataPane.setLayout(dataPaneLayout);
        dataPaneLayout.setHorizontalGroup(
            dataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        dataPaneLayout.setVerticalGroup(
            dataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        data.add(dataPane, java.awt.BorderLayout.CENTER);

        jPanel12.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 50));

        withdraw.setBackground(new java.awt.Color(28, 37, 65));
        withdraw.setLayout(new java.awt.BorderLayout());

        withdrawSel.setBackground(new java.awt.Color(11, 19, 43));

        javax.swing.GroupLayout withdrawSelLayout = new javax.swing.GroupLayout(withdrawSel);
        withdrawSel.setLayout(withdrawSelLayout);
        withdrawSelLayout.setHorizontalGroup(
            withdrawSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        withdrawSelLayout.setVerticalGroup(
            withdrawSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        withdraw.add(withdrawSel, java.awt.BorderLayout.LINE_START);

        withdrawPane.setBackground(new java.awt.Color(11, 19, 43));

        withdrawLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        withdrawLabel.setForeground(new java.awt.Color(239, 247, 246));
        withdrawLabel.setText("Withdraw");

        javax.swing.GroupLayout withdrawPaneLayout = new javax.swing.GroupLayout(withdrawPane);
        withdrawPane.setLayout(withdrawPaneLayout);
        withdrawPaneLayout.setHorizontalGroup(
            withdrawPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(withdrawLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        withdrawPaneLayout.setVerticalGroup(
            withdrawPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(withdrawLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        withdraw.add(withdrawPane, java.awt.BorderLayout.CENTER);

        jPanel12.add(withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, 50));

        profile.setBackground(new java.awt.Color(28, 37, 65));
        profile.setLayout(new java.awt.BorderLayout());

        profileSel.setBackground(new java.awt.Color(11, 19, 43));

        javax.swing.GroupLayout profileSelLayout = new javax.swing.GroupLayout(profileSel);
        profileSel.setLayout(profileSelLayout);
        profileSelLayout.setHorizontalGroup(
            profileSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        profileSelLayout.setVerticalGroup(
            profileSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        profile.add(profileSel, java.awt.BorderLayout.LINE_START);

        profilePane.setBackground(new java.awt.Color(11, 19, 43));

        profileLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        profileLabel.setForeground(new java.awt.Color(239, 247, 246));
        profileLabel.setText("Profile");

        javax.swing.GroupLayout profilePaneLayout = new javax.swing.GroupLayout(profilePane);
        profilePane.setLayout(profilePaneLayout);
        profilePaneLayout.setHorizontalGroup(
            profilePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        profilePaneLayout.setVerticalGroup(
            profilePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        profile.add(profilePane, java.awt.BorderLayout.CENTER);

        jPanel12.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 220, 50));

        sidePane.add(jPanel12, java.awt.BorderLayout.CENTER);

        getContentPane().add(sidePane, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(11, 19, 43));
        topPanel.setPreferredSize(new java.awt.Dimension(841, 40));
        topPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(11, 19, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minmize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        jPanel1.add(minmize, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 40, 40));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 0, 40, 40));

        resize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/resize.png"))); // NOI18N
        jPanel1.add(resize, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 40, 40));

        topPanel.add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(11, 19, 43));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        topPanel.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(topPanel, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(239, 247, 246));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
//        System.exit(1);
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JPanel data;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JPanel dataPane;
    private javax.swing.JPanel dataSel;
    private javax.swing.JPanel home;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homePane;
    private javax.swing.JPanel homeSel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel minmize;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel profile;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JPanel profilePane;
    private javax.swing.JLabel profilePicture;
    private javax.swing.JPanel profileSel;
    private javax.swing.JPanel project;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JPanel projectPane;
    private javax.swing.JPanel projectSel;
    private javax.swing.JLabel resize;
    private javax.swing.JPanel sidePane;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel withdraw;
    private javax.swing.JLabel withdrawLabel;
    private javax.swing.JPanel withdrawPane;
    private javax.swing.JPanel withdrawSel;
    // End of variables declaration//GEN-END:variables
}
